[project]
name = "urlproject"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.128.0",
    "greenlet>=3.3.0",
    "psycopg2-binary>=2.9.9",
    "sqlalchemy>=2.0.45",
    "uvicorn>=0.40.0",
]
